import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";
import { DemoForm } from "@/components/DemoForm";
import { cars, formatPrice } from "@/lib/cars";
export const Route = createFileRoute("/cars/$id")({
 loader: ({ params }) => { const car = cars.find(item => item.id === params.id); if (!car) throw notFound(); return car; },
 head: ({ loaderData }) => ({ meta: [{ title: loaderData ? `${loaderData.make} ${loaderData.model} | AutoElite Motors` : "Vehicle Not Found | AutoElite Motors" }, { name: "description", content: loaderData ? `Explore the ${loaderData.year} ${loaderData.make} ${loaderData.model} in the AutoElite showroom.` : "Browse the AutoElite collection." }, { property: "og:title", content: loaderData ? `${loaderData.make} ${loaderData.model} | AutoElite Motors` : "Vehicle Not Found | AutoElite Motors" }, { property: "og:description", content: loaderData ? `Explore the ${loaderData.year} ${loaderData.make} ${loaderData.model}.` : "Browse the AutoElite collection." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
 component: CarDetail,
});
function CarDetail() { const car = Route.useLoaderData(); return <main className="page-main shell"><div className="detail-layout"><div><Link to="/inventory" className="back-link"><ArrowLeft size={15}/> BACK TO INVENTORY</Link><img className="detail-photo" src={car.image} alt={`${car.make} ${car.model}`}/><div className="detail-thumbs"><img src={car.image} alt={`${car.model} exterior view`}/><img src={car.image} alt={`${car.model} side view`}/><img src={car.image} alt={`${car.model} showroom view`}/></div></div><div><div className="detail-panel"><span className="car-make">{car.year} / CERTIFIED COLLECTION</span><h1 className="display">{car.make}<br/><em>{car.model}</em></h1><strong className="detail-price">{formatPrice(car.price)}</strong><div className="spec-grid"><div><span>MILEAGE</span><strong>{car.mileage} mi</strong></div><div><span>ENGINE</span><strong>{car.engine}</strong></div><div><span>TRANSMISSION</span><strong>Automatic</strong></div><div><span>COLOR</span><strong>{car.color}</strong></div></div></div><div className="detail-panel"><h2>THE DETAILS</h2><p>{car.description}</p><div className="features-inline">{car.features.map(feature => <span key={feature}>{feature}</span>)}</div></div><div className="detail-panel"><h2>ENQUIRE ABOUT THIS CAR</h2><DemoForm selected={car.id}/></div></div></div></main> }
