import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { CarCard } from "@/components/CarCard";
import { cars } from "@/lib/cars";
export const Route = createFileRoute("/inventory")({ head: () => ({ meta: [{ title: "Inventory | AutoElite Motors" }, { name: "description", content: "Browse the AutoElite collection of luxury coupes, SUVs, and sedans." }, { property: "og:title", content: "Inventory | AutoElite Motors" }, { property: "og:description", content: "Browse the AutoElite collection of luxury coupes, SUVs, and sedans." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Inventory });
function Inventory() {
 const [search,setSearch] = useState(""); const [type,setType] = useState("All"); const [max,setMax] = useState(350000);
 const shown = cars.filter(car => `${car.make} ${car.model}`.toLowerCase().includes(search.toLowerCase()) && (type === "All" || car.type === type) && car.price <= max);
 return <main className="page-main shell"><div className="page-heading"><span className="section-label">THE AUTOELITE COLLECTION</span><h1 className="display">OUR <em>COLLECTION.</em></h1><p>Discover a hand-selected line-up of extraordinary vehicles.</p></div><div className="filter-bar"><label>SEARCH MAKE & MODEL<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search the collection..." type="search"/></label><label>VEHICLE TYPE<select value={type} onChange={e => setType(e.target.value)}><option>All</option><option>Coupe</option><option>SUV</option><option>Sedan</option></select></label><label>MAX PRICE <span className="range-label">${(max/1000).toFixed(0)}K</span><input type="range" min="100000" max="350000" step="5000" value={max} onChange={e => setMax(Number(e.target.value))}/></label></div><p className="result-count">SHOWING {shown.length} {shown.length === 1 ? "VEHICLE" : "VEHICLES"}</p>{shown.length ? <div className="car-grid" style={{marginBottom:110}}>{shown.map(car => <CarCard car={car} key={car.id}/>)}</div> : <div className="empty-state">No cars match your search. Try another make, type, or price.</div>}</main>
}
